# dev-sec.os-hardeningの再適用の無効化
# ※以下の処理の再適用に時間がかかるため
# https://github.com/dev-sec/ansible-os-hardening/blob/master/tasks/minimize_access.yml
os_hardening_enabled: false

common_ssh_allow_countries:
  - JP
  - US

dehydrated_cfg:
  challengetype: dns-01

dehydrated_domains:
  - name: "{{ domain }}"
    domains:
      - "{{ domain }}"
      - "www.{{ domain }}"

dehydrated_auto_execute: false

dehydrated_hook_initialize: |
  export PROVIDER=cloudflare
  export LEXICON_CLOUDFLARE_USERNAME="{{ lookup('env', 'CLOUDFLARE_EMAIL') }}"
  export LEXICON_CLOUDFLARE_TOKEN="{{ lookup('env', 'CLOUDFLARE_TOKEN') }}"

dehydrated_hook_deploy_challenge: |
  lexicon ${PROVIDER} create ${DOMAIN} TXT --name="_acme-challenge.${DOMAIN}." --content="${TOKEN_VALUE}"
  sleep 30

dehydrated_hook_clean_challenge: |
  lexicon ${PROVIDER} delete ${DOMAIN} TXT --name="_acme-challenge.${DOMAIN}." --content="${TOKEN_VALUE}"

dehydrated_hook_deploy_cert: |
  if [ -e /lib/systemd/system/nginx.service ]; then
    /bin/systemctl reload nginx
  fi

nginx_cfg:
  http:
    ssl:
      dhparam: "{{ nginx_dh_key_path }}"

nginx_vhosts:
  - name: default
    default: yes
    server_name: "{{ domain }}"
    access_log: /var/log/nginx/access.log
    error_log: /var/log/nginx/error.log
    document_root: /var/www/html
    includes:
      - conf.d/security.conf
    index:
      - index.html
      - index.htm
      - index.php
    locations:
      - pattern: /
        content: |
          try_files $uri $uri/ /index.php?$query_string;
      - pattern: "\\.php"
        match_type: "~"
        content: |
          fastcgi_pass unix:/var/run/php/php{{ php_default_version }}-fpm.sock;
          include snippets/fastcgi-php.conf;
      - pattern: "/\\.ht"
        match_type: "~"
        content: "deny all;"
    ssl:
      certificate: /var/lib/dehydrated/certs/{{ domain }}/fullchain.pem
      certificate_key:  /var/lib/dehydrated/certs/{{ domain }}/privkey.pem
      hsts: "max-age=15768000;"
      stapling: yes
      stapling_verify: yes
  - name: default_non_ssl
    server_name: "{{ domain }}"
    includes:
      - conf.d/security.conf
      - snippets/redirect_https.conf
  - name: status
    server_name: localhost
    listen: 8080
    access_log: 'off'
    locations:
      - pattern: /nginx_status
        content: |
          stub_status on;
          allow 127.0.0.1;
          deny all;

mackerel_agent_install_agent_plugins: true

mackerel_agent_cfg:
  plugin:
    metrics:
      nginx: /usr/bin/mackerel-plugin-nginx
