---
ansible:
  group_vars:
    all:
      mariadb_cfg:
        mysqld:
          ## General
          sql_mode:
            - ONLY_FULL_GROUP_BY
            - STRICT_TRANS_TABLES
            - NO_ZERO_IN_DATE
            - NO_ZERO_DATE
            - ERROR_FOR_DIVISION_BY_ZERO
            - NO_AUTO_CREATE_USER
            - NO_ENGINE_SUBSTITUTION
          bind_address: 127.0.0.1
          datadir: /var/lib/mysql
          socket: /var/run/mysqld/mysqld.sock
          innodb_data_home_dir: /var/lib/mysql
          ## Network
          max_connections: 123
          connect_timeout: 10
          skip_name_resolve: no
          max_allowed_packet: 4K
          interactive_timeout: 3600
          wait_timeout: 600
          table_open_cache: 200
          thread_cache_size: 130
          table_definition_cache: 550
          query_cache_limit: 10M
          query_cache_size: 32M
          query_cache_type:  2
          ## InnoDB General
          innodb_file_per_table: yes
          innodb_flush_log_at_trx_commit: 1
          innodb_buffer_pool_size: 500M
          innodb_log_file_size: 100M
          innodb_log_files_in_group: 3
          innodb_additional_mem_pool_size: 48M
          innodb_log_buffer_size: 32M
          innodb_strict_mode: yes
          innodb_large_prefix: yes
          innodb_file_format: Barracuda
          max_heap_table_size: 16M
          tmp_table_size: 16M
          sort_buffer_size: 128K
          join_buffer_size: 256K
          read_buffer_size: 384K
          read_rnd_buffer_size: 512K
          key_buffer_size: 150M
          ## Thread Buffer
          myisam_sort_buffer_size: 64M
          # -----------------
          # Logging
          # -----------------
          slow_query_log: no
          long_query_time: 7
          log_warnings: 1
          min_examined_row_limit: 5
          log_queries_not_using_indexes: yes
          log_slow_admin_statements: no
          slow_query_log_file: /var/log/mysql/molecule_slow.log
          general_log: yes
          general_log_file: /var/log/mysql/molecule_general.log
          # -----------------
          # Replication
          # -----------------
          gtid_domain_id: 1
          server_id: 2
          log_bin: mysql-bin
          binlog_format: ROW
          expire_logs_days: 3
          read_only: no
          log_slave_updates: yes

dependency:
  name: galaxy
driver:
  name: vagrant
vagrant:
  platforms:
    - name: stretch
      box: histudy/stretch
  providers:
    - name: virtualbox
      type: virtualbox
      options:
        memory: 1024
        cpus: 1
  instances:
    - name: mariadb
      ansible_groups:
        - molecule
verifier:
  name: serverspec
