---
os_auth_pw_max_age: 99999
ssh_allow_root_with_key: true
ssh_use_pam: true
sftp_enabled: true

domain: histudy.jp

common_groups:
  - name: histudy
  - name: kakogawa_infra
  - name: webadmin

common_users:
  - name: wate
    admin: true
    groups:
      - histudy
      - kakogawa_infra
      - webadmin
    authorized_keys:
      - "https://github.com/wate.keys"
  - name: sperkbird
    admin: true
    groups:
      - histudy
      - kakogawa_infra
    authorized_keys:
      - "https://github.com/sperkbird.keys"
  - name: nogajun
    admin: true
    groups:
      - histudy
      - webadmin
    authorized_keys:
      - "https://github.com/nogajun.keys"
  - name: 223n
    admin: true
    groups:
      - histudy
      - kakogawa_infra
      - webadmin
    authorized_keys:
      - "https://github.com/223n.keys"
  - name: fu7mu4
    groups:
      - histudy
    authorized_keys:
      - "https://github.com/fu7mu4.keys"

mackerel_agent_api_key: "{{ lookup('env', 'MACKEREL_API_KEY') }}"

common_cron_geoip_update:
  hour: 1
  minute: 23

dehydrated_cron:
  hour: 2
  minute: 34
