---
ansible:
  group_vars:
    default:
      mackerel_agent_api_key: "{{ lookup('env', 'MACKEREL_API_KEY') }}"
    enable_all:
      mackerel_agent_api_key: "{{ lookup('env', 'MACKEREL_API_KEY') }}"
      mackerel_agent_install_agent_plugins: yes
      mackerel_agent_install_check_plugins: yes
      mackerel_agent_active_and_enabled_on_system_startup: yes
    disable_all:
      mackerel_agent_api_key: "disable_all_api_key"
      mackerel_agent_install_agent_plugins: no
      mackerel_agent_install_check_plugins: no
      mackerel_agent_active_and_enabled_on_system_startup: no
dependency:
  name: galaxy
driver:
  name: vagrant
vagrant:
  platforms:
    - name: stretch
      box: histudy/stretch
  providers:
    - name: virtualbox
      type: virtualbox
      options:
        memory: 512
        cpus: 1
  instances:
    - name: mackerel-agent
      ansible_groups:
        - default
    - name: enable-all
      ansible_groups:
        - enable_all
    - name: disable-all
      ansible_groups:
        - disable_all
verifier:
  name: serverspec
