---
ansible:
  group_vars:
    all:
      mackerel_agent_cfg:
        pidfile: /var/run/mackerel-agent.pid
        root: /var/lib/mackerel-agent
        verbose: no
        display_name: My Host
        http_proxy: http://localhost:8080
        roles:
          - My-Service:app
          - Another-Service:db
        host_status:
          on_start: working
          on_stop: poweroff
        filesystems:
          ignore: /dev/ram.*
          use_mountpoint: yes
        plugin:
          metrics:
            apache2: /usr/bin/mackerel-plugin-apache2
            mailq: /usr/bin/mackerel-plugin-mailq -M postfix
          checks:
            log: "/usr/bin/check-log --file=/path/to/file --pattern=REGEXP --warning-over=N --critical-over=N"
            procs:
              command: "/usr/bin/check-procs --pattern=PROCESS_NAME --state=STATE --warning-under=N"
            load_average:
              command: "/usr/bin/check-load -w 3,2,1 -c 3,2,1"
              # optional
              notification_interval: 60
              max_check_attempts: 1
              check_interval: 5
              timeout_seconds: 45
              prevent_alert_auto_close: yes
              memo: '「"(ダブルクォート)」や「\(バックスラッシュ)」は自動でエスケープされます'
              env:
                ENV_NAME1: value1
                ENV_NAME2: value2
              action:
                command: pa -auxf
                env:
                  ENV_NAME1: value1
                  ENV_NAME2: value2
                user: mackerel
  host_vars:
    mackerel-agent:
      mackerel_agent_api_key: "{{ lookup('env', 'MACKEREL_API_KEY') }}"
    enable-all:
      mackerel_agent_api_key: "{{ lookup('env', 'MACKEREL_API_KEY') }}"
      mackerel_agent_install_agent_plugins: yes
      mackerel_agent_install_check_plugins: yes
      mackerel_agent_active_and_enabled_on_system_startup: yes
    disable-all:
      mackerel_agent_api_key: "disable_all_api_key"
      mackerel_agent_install_agent_plugins: no
      mackerel_agent_install_check_plugins: no
      mackerel_agent_active_and_enabled_on_system_startup: no
dependency:
  name: galaxy
driver:
  name: vagrant
vagrant:
  platforms:
    - name: stretch
      box: histudy/stretch
  providers:
    - name: virtualbox
      type: virtualbox
      options:
        memory: 512
        cpus: 1
  instances:
    - name: mackerel-agent
      ansible_groups:
        - molecule
    - name: enable-all
      ansible_groups:
        - molecule
    - name: disable-all
      ansible_groups:
        - molecule
verifier:
  name: serverspec
